A/B testing of a service
gip-inclusion/dora-front pull request #276
Opened 2023-06-14 12:57 UTC by AlexandreCantin

https://trello.com/c/99aQni8p/743-fiche-service-a-b-testing

2023-06-15 12:28 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fiche service : A/B Testing](https://trello.com/c/99aQni8p/743-fiche-service-a-b-testing)

2023-06-19 09:09 UTC, cedricr requested changes
C'est très cool, mais il y a quelques points à régler.

Un defaut de fond cependant, mais plus pour la prochaine fois:
- ces copies de fichier sont extrement difficile à reviewer, on perd complètement les diffs, donc autant dire que je ne les ai pas vérifiés
- une fois que l'expérience sera terminée, il faudra faire une passe de nettoyage complexe pour enlever la branche qu'on ne garde pas. Idéalement, l'AB testing devrait préserver au maximum la structure des fichiers, et juste insérer des tests, facile à retrouver par une recheche, à chaque modification.

2023-06-19 12:47 UTC, AlexandreCantin commented on src/lib/utils/ab-testing.ts
> +        abTest.groupNames[between(1, abTest.groupNames.length) - 1];
Je l'avais testé de mon côté dans un REPL NodeJS mais je vais un test unitaire (en regardant entre >= 32 et <= 34) :)

2023-06-19 14:05 UTC, AlexandreCantin commented
`Idéalement, l'AbTesting devrait préserver au maximum la structure des fichiers` => alors je suis d'accord mais, pour le coup, (j'ai jugé que) les différences étaient vraiment trop importantes pour conserver la structure… 😓

D'ailleurs, et idéalement , un AbTesting fait varier un texte et/ou une couleur et dans cette expérience, on avait vraiment un gros changement de design entre l'ancienne et la nouvelle version.
Avec juste la couleur de fond du bloc `mobiliser`, je l'aurais fait sans souci mais c'est moins simple quand il s'agit de faire cohabiter deux designs entre eux… 😅

2023-06-20 09:23 UTC, cedricr requested changes
On y est presque!
Tu as fait les tests manuellement jusqu'à Plausible?

2023-06-20 09:23 UTC, cedricr commented on src/lib/utils/ab-testing.ts
> +    Sentry.captureException(
Les fonctions de log sont rassemblées dans lib/utils/logger.ts; et ici tu n'as pas d'exception en plus, donc ce cerait 'log'

2023-06-20 09:23 UTC, cedricr commented on src/lib/utils/ab-testing.ts
> +      console.log("keep", abTestName);
Pense à enlever les logs

2023-06-20 13:08 UTC, AlexandreCantin commented
`Tu as fait les tests manuellement jusqu'à Plausible ?` Oui c'est bon :)

2023-06-20 14:25 UTC, cedricr approved these changes

2023-06-20 15:19 UTC, merged