Tracking: url dédiée aux services mobilisables
gip-inclusion/dora-front pull request #320
Opened 2023-08-09 15:22 UTC by AlexandreCantin

https://trello.com/c/N75MJ4BK/851-orientation-funnel-sur-plausible

=> des tests en pré-prod seront à mener et des actions post-mep aussi :)

2023-08-09 21:05 UTC, cedricr requested changes

2023-08-09 21:05 UTC, cedricr commented on src/lib/utils/plausible.ts
> +    const customMobilisableUrl = url.pathname.replace(
hum bof, c'est un peu un hack quand même... Si on veut stocker l'info "ce service est mobilisable" en back, rajoutons un booléen 'mobilisable' à l'événement, ça sera beaucoup plus facile à maintenir, et à exploiter dans metabase

2023-08-09 21:05 UTC, cedricr commented on src/lib/utils/plausible.ts
> +    plausible("pageview", { u: customMobilisableUrl });
Les funnels ne necessitent pas des 'pageview' donc on peut envoyer un événement 'service-mobilisable' par exemple, plutot que de tricher sur l'URL

2023-08-10 14:35 UTC, AlexandreCantin commented on src/lib/utils/plausible.ts
> +    const customMobilisableUrl = url.pathname.replace(
Du coup, une nouvelle PR a vu le jour sur le back :)

2023-08-14 09:31 UTC, cedricr approved these changes
LGTM; ne pas oublier d'ajouter une carte post-MEP pour mettre à jour le funnel!

2023-08-29 16:38 UTC, cedricr commented on src/lib/utils/plausible.ts
> +      _track("service-mobilisable", _getServiceProps(service, true));
en fait, si on avait pas ça, il suffirait de tout faire en back, qui peut très bien regarder de son coté si le service est mobilisable ou pas, au moment de la creation de l'évenement. 
Et 'mobilisable' pourrait être une propriété du service, calculé en back, pour éviter au front de refaire la logique pour déterminer si on affiche le bouton ou pas. Je passe cette PR en draft, et on en parle à ton retour.

2023-09-04 15:39 UTC, cedricr commented on src/lib/utils/plausible.ts
> +    if (get(token) && mobilisable) {
hum, à discuter, le service est mobilisable même si je ne suis pas loggué non? mais on risque de tracker 2 fois si l'utilisateur se connecte pour le mobiliser, c'est ça?

2023-09-06 13:32 UTC, merged