Nouvelle recherche
gip-inclusion/dora-front pull request #325
Opened 2023-08-17 14:18 UTC by AlexandreCantin

2023-08-17 14:18 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Amélioration de la recherche (thématique / besoins)](https://trello.com/c/anqKmEDE/806-am%C3%A9lioration-de-la-recherche-th%C3%A9matique-besoins)

2023-08-30 08:36 UTC, cedricr requested changes

2023-08-30 08:36 UTC, cedricr commented on src/lib/components/inputs/obsolete/select-field.svelte
Étant donné qu'on n'a plus de groupes, je pense que c'est l'occasion de se débarasser de ce composant pour revenir au select principal. Quite à créer, *si nécessaire* un select-subcategories-field qui en dériverait pour gérer le fonctionnement particulier (--all, etc.)

En profiter pour supprimer toute la gestion des optGroup/optGroupKey dans le code si possible

2023-08-30 08:36 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +    refreshDisabled = true;
à faire avant le goto peut-être pour plus de clarté

2023-08-30 08:36 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +  function handleCategoryChange(isInit = false) {
à remonter, pour ne pas mélanger déclarations et fonctions

2023-08-30 08:36 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +    if (!isInit) {
bof, mets plutot ce code dans le onMount avant l'appel?

2023-08-30 08:36 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +        subCategoryIds = [`${categoryId}--all`];
non, au refresh de la page tu perds les eventuelles sous-categories selectionnées

2023-08-30 08:36 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +        ...getChoicesFromKey(categoryId, servicesOptions.subcategories),
je ne suis pas plus fan qu'à l'époque d'avoir des fonctions au nom super génériques, mais qui ne s'appliquent qu'à la gestion des catégories et sous-catégories. À mon avis ça vaut le coup de simplifier un peu tout ça.

2023-09-11 13:53 UTC, AlexandreCantin commented on src/lib/components/specialized/service-search.svelte
> +        ...getChoicesFromKey(categoryId, servicesOptions.subcategories),
Elle faisait une ligne et était utilisé deux fois
J'ai mis directement le corps de la fonction (qui devient plus précis avec le nom des variables contextualisées).

2023-09-11 14:10 UTC, AlexandreCantin commented on src/lib/components/specialized/service-search.svelte
> +  function handleCategoryChange(isInit = false) {
J'ai plutôt remonter la déclaration `const categories = ……`

2023-09-13 14:46 UTC, AlexandreCantin commented
![Capture d’écran 2023-09-13 à 15 51 59](https://github.com/gip-inclusion/dora-front/assets/1846641/e74f2df5-3c36-4404-89c8-fc8da3524bfa)

@cedricr malheureusement le design est assez différent… notamment sur les aspect multiple : bloc violet (qu'on peut retirer certes) et pas de reprise des champs sélectionnés dans le champs texte
De plus, je ne suis pas sûr qu'Andrei souhaitait un champs d'auto-completion…

C'est possible d'adapter le `select` avec de nouvels options… À voir si cela vaut le coup 🤔

2023-09-14 12:32 UTC, cedricr commented
> ![Capture d’écran 2023-09-13 à 15 51 59](https://user-images.githubusercontent.com/1846641/267680344-e74f2df5-3c36-4404-89c8-fc8da3524bfa.png)
> 
> @cedricr malheureusement le design est assez différent… notamment sur les aspect multiple : bloc violet (qu'on peut retirer certes) et pas de reprise des champs sélectionnés dans le champs texte De plus, je ne suis pas sûr qu'Andrei souhaitait un champs d'auto-completion…
> 
> C'est possible d'adapter le `select` avec de nouvels options… À voir si cela vaut le coup 🤔

@AlexandreCantin ok c'est pas l'urgence alors, mais il faudra qu'on converge un jour ou l'autre -- on ne peut pas continuer à maintenir des versions multiples de chaque composant…

2023-09-14 12:57 UTC, cedricr approved these changes

2023-09-14 15:57 UTC, merged