Modification des wordings pour le rattachement
gip-inclusion/dora-front pull request #328
Opened 2023-08-22 15:39 UTC by AlexandreCantin

https://trello.com/c/oXUU5uyb/872-modification-de-la-phrase-sur-lihm-auth-rattachement

2023-08-22 15:39 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modification de la phrase sur l'ihm auth/rattachement](https://trello.com/c/oXUU5uyb/872-modification-de-la-phrase-sur-lihm-auth-rattachement)

2023-08-29 09:16 UTC, cedricr requested changes

2023-08-29 09:16 UTC, cedricr commented on src/routes/auth/rattachement/+page.svelte
> +      description="Pour accéder a toutes les fonctionnalités, merci de nous indiquer la structure dans laquelle vous travaillez :"
```suggestion
      description="Pour accéder à toutes les fonctionnalités, merci de nous indiquer la structure dans laquelle vous travaillez :"
```

2023-08-29 09:16 UTC, cedricr commented on src/routes/structures/[slug]/pending-notice.svelte
> +    En cas de difficultés, n’hésitez pas à nous contacter.
le "nous contacter" est un lien sur la maquette.

2023-08-30 10:19 UTC, cedricr requested changes

2023-08-30 10:19 UTC, cedricr commented on src/routes/structures/[slug]/pending-notice.svelte
> +    {#if admins.length}
Toujours faux si on ne fait pas partie de la structure (sauf pour les superadmins). Le back ne fournit pas la liste des utilisateurs.
À discuter.

2023-09-04 16:57 UTC, cedricr requested changes

2023-09-04 16:57 UTC, cedricr commented on src/routes/structures/[slug]/pending-notice.svelte
> +          (admin) => `${admin.user.firstName.charAt(0)}. ${admin.user.lastName}`
Très fragile s'il manque le firstname ou le lastname

2023-09-04 16:58 UTC, merged