Save search
gip-inclusion/dora-front pull request #333
Opened 2023-09-11 14:25 UTC by AlexandreCantin

2023-09-25 12:52 UTC, cedricr requested changes

2023-09-25 12:52 UTC, cedricr commented on src/lib/types.ts
> +  categories: string[];
voir le commentaire en back -- peut-être au singulier?

2023-09-25 12:52 UTC, cedricr commented on src/lib/utils/saved-search.ts
> +  const url = `${getApiURL()}/services/save-search/`;
les URLs ne sont pas bonnes, voir les commentaires back

2023-09-25 12:52 UTC, cedricr commented on src/lib/utils/saved-search.ts
> +  for (let i = 0; i < userSavedSearchs.length; i++) {
plus élégant: `userSavedSearchs.some(search => ...)`

2023-09-25 12:52 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +          label="Recherche déjà sauvegardé"
'Alerte déjà créée' plutôt?

2023-09-25 12:52 UTC, cedricr commented on src/routes/_index/menu-mon-compte.svelte
> +      class:text-magenta-cta={$page.url.pathname === "/alertes"}
```suggestion
      class:text-magenta-cta={$page.url.pathname === "/mes-alertes"}
```
On va sans doute faire évoluer ça, mais ça me parait plus clair comme URL (j'aurais du le faire pour les favoris aussi d'ailleurs)

2023-09-25 12:52 UTC, cedricr commented on src/routes/alertes/+page.svelte
> +            Vous n’avez pas encore crée des alertes
```suggestion
            Vous n’avez pas encore créé d’alerte
```

2023-09-25 12:52 UTC, cedricr commented on src/routes/alertes/+page.svelte
> +            href="https://aide.dora.inclusion.beta.gouv.fr/fr/category/quoi-de-neuf-es1img/"
C'est une URL temporaire?

2023-09-25 12:52 UTC, cedricr commented on src/routes/alertes/+page.ts
> +
Page authentifiée, tu peux désactiver le SSR

`export const ssr = false;`

2023-09-25 12:52 UTC, cedricr commented on src/routes/structures/[slug]/antennes/list.svelte
> +  // import { API_URL, CANONICAL_URL } from "$lib/env";
commentaires à nettoyer dans le fichier, mais pourquoi il y a des modifs ici? C'est eslint qui rale?

2023-09-25 12:52 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +    goto(`recherche?${query}`);
pas testé mais ça vaut peut-etre le coup de rajouter noScroll: true au goto.

2023-09-25 12:52 UTC, cedricr commented on src/routes/alertes/saved-search-card.svelte
> +  .form-container :global(form) {
Je trouve ça dommage de dégainer toute la machinerie des formulaires et de la validation, alors qu'il n'y a pas de champs "libres", et que tu pourrais te contenter d'un select et d'un bouton, et du coup éviter de devoir bidouiller les styles comme ça :man_shrugging:

2023-09-25 17:45 UTC, AlexandreCantin commented on src/routes/alertes/+page.svelte
> +            href="https://aide.dora.inclusion.beta.gouv.fr/fr/category/quoi-de-neuf-es1img/"
J'ai mis le code en commentaire, l'article n'existe pas encore…

2023-09-25 17:46 UTC, AlexandreCantin commented on src/routes/alertes/+page.svelte
> +            href="https://aide.dora.inclusion.beta.gouv.fr/fr/category/quoi-de-neuf-es1img/"
Je vais aussi créer un ticket en "bloqué" pour ce point précis

2023-09-25 17:53 UTC, AlexandreCantin commented on src/routes/structures/[slug]/antennes/list.svelte
> +  // import { API_URL, CANONICAL_URL } from "$lib/env";
En effet, malgré le fait que je n'ai pas touché le fichier, eslint a râlé car il y a pas mal de variables non utilisées… (c'est d'ailleurs le cas sur `main` => je vais supprimer ce contenu - même s'il est hors du contexte de cette PR)

2023-09-26 11:41 UTC, AlexandreCantin commented on src/lib/components/specialized/service-search.svelte
> +    goto(`recherche?${query}`);
J'ai testé et il n'y a pas besoin de le faire… :)

2023-09-28 14:19 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +    goto(`recherche?${query}`);
je pense que c'est mieux: si tu as scrollé sur la page, et que tu cliques sur actualiser la recherche, en l'état ça remet le scroll à zero. En rajoutant cette option, par contre, ça ne bouge pas, ce qui est plus naturel.

2023-09-28 15:44 UTC, cedricr requested changes

2023-09-28 15:44 UTC, cedricr commented on src/lib/types.ts
> +export type Frequency = "NEVER" | "TWO_WEEKS" | "MONTHLY";
c'est trop vague pour un type global. SavedSearchNotificationFrequency plutot?

2023-09-28 15:44 UTC, cedricr commented on src/lib/utils/saved-search.ts
Les requetes vont plutot dans $lib/requests/

2023-10-04 15:22 UTC, cedricr approved these changes

2023-10-05 10:12 UTC, merged