Ajout des thématiques dans l'export xlsx du tdb
gip-inclusion/dora-front pull request #335
Opened 2023-09-12 13:05 UTC by AlexandreCantin

https://trello.com/c/lQqqTk5F

2023-09-12 13:38 UTC, cedricr requested changes

2023-09-12 13:38 UTC, cedricr commented on src/routes/admin/structures/+page.svelte
> +        "Thématiques": structure.categories.filter(Boolean).map(
Pas sur de bien comprendre cette ligne, c'est quoi ce filter(Boolean)?

Par ailleurs, si une catégorie n'est pas trouvée dans les services options, tu vas quand même joindre le null dans la chaine finale. Ça serait plus élégant de commencer par le map, puis de filtrer les non nulles, et enfin seulement de faire le join

2023-09-13 08:10 UTC, AlexandreCantin commented on src/routes/admin/structures/+page.svelte
> +        "Thématiques": structure.categories.filter(Boolean).map(
En effet, j'ai commencé à gérer les soucis de `undefined` dans les catégories avant celui les labels…

2023-09-13 08:44 UTC, cedricr requested changes

2023-09-13 08:44 UTC, cedricr commented on src/routes/admin/structures/+page.svelte
> +          .filter(Boolean)
Je connaissais pas ce pattern, mais je dois dire que je ne suis pas fan, peut-être une question d'habitude; le value => !!value me parait tout aussi lisible.
Dans ce cas, on veut filtrer les eventuels undefined provenant du ?,, donc je prefère largement le `!= null` qui reflète mieux l'intention.

2023-09-13 08:44 UTC, cedricr commented on src/routes/admin/structures/+page.svelte
> +        Nom: structure.name,
le // prettier-ignore était là pour éviter d'enlever les guillemets et d'avoir un mélange de clés entourées de guillemets et d'autre sans.

2023-09-20 09:31 UTC, cedricr approved these changes

2023-09-20 10:05 UTC, merged