Modification de la création d'antennes
gip-inclusion/dora-front pull request #336
Opened 2023-09-13 08:36 UTC by AlexandreCantin

https://trello.com/c/l3jIJoPp/885-changer-laction-du-bouton-cr%C3%A9ation-dantennes

2023-09-13 08:50 UTC, cedricr requested changes

2023-09-13 08:50 UTC, cedricr commented on src/routes/structures/[slug]/antennes/new-branch-modal.svelte
> +      ainsi la possibilité d’afficher <strong>propres offres</strong> et d’être
```suggestion
      ainsi la possibilité d’afficher <strong>ses propres offres</strong> et d’être
```
Attention à la relecture ; je ne relis pas le reste, mais ça vaut sans doute le coup que tu le fasses ;-)

2023-09-13 13:13 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Changer l'action du bouton création d'antennes](https://trello.com/c/l3jIJoPp/885-changer-laction-du-bouton-cr%C3%A9ation-dantennes)

2023-09-14 12:29 UTC, cedricr requested changes
Texte à mettre à jour avec ce qu'on a dit ce matin

2023-09-14 14:18 UTC, cedricr approved these changes

2023-09-14 15:59 UTC, merged