Ajout des favoris de data-inclusion
gip-inclusion/dora-front pull request #351
Opened 2023-10-05 13:43 UTC by AlexandreCantin

https://trello.com/c/ewH9B9sn/937-permettre-de-mettre-un-service-datainclusion-en-favori

2023-10-05 13:43 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Permettre de mettre un service data·inclusion en favori](https://trello.com/c/ewH9B9sn/937-permettre-de-mettre-un-service-datainclusion-en-favori)

2023-10-18 08:08 UTC, cedricr requested changes

2023-10-18 08:08 UTC, cedricr commented on src/routes/(modeles-services)/services/[slug]/service-header.svelte
> -<Bookmarkable slug={service.slug} let:onBookmark let:isBookmarked>
On ne peut plus bookmarquer dans le header?

2023-10-18 09:01 UTC, AlexandreCantin commented on src/routes/(modeles-services)/services/[slug]/service-header.svelte
> -<Bookmarkable slug={service.slug} let:onBookmark let:isBookmarked>
Non, c'est le bloc en bas à droite :
<img width="462" alt="Capture d’écran 2023-10-18 à 10 57 29" src="https://github.com/gip-inclusion/dora-front/assets/1846641/6dbcc218-6437-4af4-8af5-da47f83cedde">

En fait, le bouton avait retiré mais pas le `<Bookmarkable />`

2023-11-01 15:19 UTC, cedricr approved these changes

2023-11-01 15:20 UTC, merged