Retrait de code non utilisé
gip-inclusion/dora-front pull request #354
Opened 2023-10-10 10:14 UTC by AlexandreCantin

Proche mais hors-sujet vis-à-vis de :
https://trello.com/c/q3dwAGpz/76-nettoyer-les-endpoints-qui-ne-sont-plus-utilis%C3%A9s-par-le-front

2023-10-10 10:14 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Nettoyer les endpoints qui ne sont plus utilisés par le front](https://trello.com/c/q3dwAGpz/76-nettoyer-les-endpoints-qui-ne-sont-plus-utilis%C3%A9s-par-le-front)

2023-10-18 08:17 UTC, cedricr requested changes

2023-10-18 08:17 UTC, cedricr commented on src/lib/requests/admin.ts
> +/*
Tu peux l'enlever complètement, je pense qu'on ne reviendra pas sur la modération de services, en tout cas pas sous cette forme.

2023-10-18 08:44 UTC, cedricr approved these changes

2023-10-18 08:48 UTC, merged