Permettre de rendre des structures obsolètes
gip-inclusion/dora-front pull request #355
Opened 2023-10-12 12:44 UTC by AlexandreCantin

https://trello.com/c/H95GIKGs/955-evolutions-espace-gestionnaire-de-territoire-bouton-structure-obsol%C3%A8te

2023-10-12 12:44 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Evolutions / espace gestionnaire de territoire => Bouton "Structure obsolète"](https://trello.com/c/H95GIKGs/955-evolutions-espace-gestionnaire-de-territoire-bouton-structure-obsol%C3%A8te)

2023-10-18 08:36 UTC, cedricr requested changes
Il faut aussi désindexer ces structures des moteurs de recherche, voir src/routes/(endpoints)/sitemap.xml/+server.ts

2023-10-18 08:36 UTC, cedricr commented on src/routes/admin/structures/structures-table.svelte
> +        <Button
comment on fait l'action contraire?

2023-10-18 09:24 UTC, AlexandreCantin commented on src/routes/admin/structures/structures-table.svelte
> +        <Button
Deux possibilités : via l'admin (mais nécessite une intervention du staff Dora); soit par un bouton dans la catégorie `Obsolete`
Je vais pinguer Yoann pour voir ce qu'il en pense…

2023-10-18 13:46 UTC, AlexandreCantin commented on src/routes/admin/structures/structures-table.svelte
> +        <Button
Il a choisi le button de retour en arrière ! (en gros, un `else`)

2023-10-18 14:50 UTC, cedricr requested changes

2023-10-18 14:50 UTC, cedricr commented on src/routes/admin/structures/structures-table.svelte
>      await modifyStructure(structure);
Juste, pour alléger la requete, et éviter d'écraser quoi que ce soit:
`    await modifyStructure({ slug: structure.slug, isObsolete: structure.isObsolete });
`

2023-10-19 15:14 UTC, merged