Ajout de la gestion multi-départements
gip-inclusion/dora-front pull request #380
Opened 2024-02-29 17:16 UTC by ikarius

https://trello.com/c/J2leGHTB/1068-un-gestionnaire-peut-g%C3%A9rer-plusieurs-d%C3%A9partements

Pour les utilisateurs gestionnaires uniquement.

Une liste déroulante avec les départements en gestion est maintenant affiché dans l'espace d'administration.

2024-03-05 15:02 UTC, cedricr requested changes

2024-03-05 15:02 UTC, cedricr commented on src/routes/admin/structures/+page.ts
> +    departments = await Promise.all(user.departments.map(searchAdminDivision));
alors tant que c’est 2 ou 3 départements, ça me choque pas, mais ce truc ça va rapidement finir avec des gens à qui on met 50 départements, voir tous, et ça risque de faire 99 requetes envoyées...
Je vais regarder si on a déjà une alternative sur le front, sinon ça me choquerait pas d’y avoir un json des 100 departements

2024-03-12 09:10 UTC, ikarius commented on src/routes/admin/structures/+page.svelte
> +        Chargement en cours…
Je l'aurais bien vu un poil plus gros : 
![image](https://github.com/gip-inclusion/dora-front/assets/147232/baa4896c-9de8-441e-83fc-955127c55cbc)

2024-03-12 09:33 UTC, ikarius commented on src/routes/admin/structures/department-list.svelte
> +  );
Je vois pas bien l'interaction une fois les départements chargés. Il y a besoin d'autres tris après le chargement ?
Sinon ça peut être trié coté backend aussi.

2024-03-12 09:55 UTC, ikarius commented on src/routes/admin/structures/department-list.svelte
> +  let:onClose={onCloseParent}
Je ne comprenais pas d'où venait `onCloseParent`, mais on est bien sur un alias local du `onClose` de `ButtonMenu` ?

2024-03-12 09:59 UTC, ikarius commented
LGTM !
(forcément, je suis à l'origine de la PR et je peux pas approuver directement...)

Merci pour le remaniement, j'ai pris un peu de temps pour aller au fond des aspects que je ne saisissais pas dans tes modifications.
Juste quelques nit et remarques pour ma connaissance perso.

Et juste un truc, je ne sais pas si c'est voulu / normal, sur Firefox, la bordure bleue lors d'une action sur le bouton : 

![image](https://github.com/gip-inclusion/dora-front/assets/147232/37cde096-4fb8-41fa-9b18-f4402702eed5)

2024-03-12 10:06 UTC, cedricr commented on src/routes/admin/structures/department-list.svelte
> +  let:onClose={onCloseParent}
Oui c’est bien ça.

2024-03-12 10:08 UTC, cedricr commented on src/routes/admin/structures/+page.svelte
> +        Chargement en cours…
Ok, je l’ai mis en gras. Si je le passe en plus gros, ça risque de faire bouger la carte lors de son apparition/disparition

2024-03-12 10:09 UTC, cedricr commented on src/routes/admin/structures/department-list.svelte
> +  );
:+1:

2024-03-12 14:02 UTC, merged