Chore/update readme and env template
gip-inclusion/dora-front pull request #386
Opened 2024-03-25 17:26 UTC by ggounot

2024-03-25 18:46 UTC, cedricr requested changes
:tada:

2024-03-25 18:46 UTC, cedricr commented on README.md
> +  - La valeur `"https://api.dora.incubateur.net"` permet de connecter le font sur la preprod et ainsi éviter une mise en place locale du back ;
```suggestion
  - La valeur `"https://api.dora.incubateur.net"` permet de connecter le front sur la preprod et ainsi éviter une mise en place locale du back ;
```

2024-03-25 20:34 UTC, ggounot commented on README.md
> +  - La valeur `"https://api.dora.incubateur.net"` permet de connecter le font sur la preprod et ainsi éviter une mise en place locale du back ;
Corrigé dans 1ceece7963925f55ccf3b25f6ebb8de9a60de38b

2024-03-26 08:06 UTC, cedricr approved these changes

2024-03-26 13:26 UTC, merged