Modalites orientation (formulaire + fiche)
gip-inclusion/dora-front pull request #427
Opened 2024-07-16 07:41 UTC by ggounot

2024-07-16 12:38 UTC, ggounot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Modalités d'orientation : configuration niveau service / Affichage sur Fiche Service](https://trello.com/c/KUZ3FJKi/49-modalit%C3%A9s-dorientation-configuration-niveau-service-affichage-sur-fiche-service)

2024-07-29 14:43 UTC, ikarius commented on src/lib/components/display/linkify.svelte
> +            const email = match.replace("mailto:", "");
_nit_: tu aurais aussi pu faire des groupes, mais je ne suis pas sur que le code d'exploitation TS rende la chose plus lisible

2024-07-29 14:56 UTC, ikarius commented on src/lib/components/display/linkify.svelte
> +      rel="noopener ugc"
_til_ : `ugc` et dommage qu'on doivent encore se farcir ces `noopener`.
Le web nécessite vraiment une connaissance encyclopédique désormais.

2024-07-29 15:57 UTC, ikarius commented on src/lib/validation/schemas/service.ts
> +        "completer-le-formulaire-dadhesion"
_nit_ : même remarque que sur le back avec les enums de `data-inclusion-schema`. N'étant pas spécialiste, il y aurait pas un moyen de synchroniser les schémas JSON générés par D·I pour en faire des types / enums ?

2024-07-29 16:32 UTC, ikarius commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
> +
Ça me parle un peu plus comme ça 👍🏻

2024-07-29 16:33 UTC, ikarius commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
> +        dispatch("trackMobilisation");
_nit_ : comme il est tard, et que j'ai très chaud, si tu as envie de détailler l'utilité de `dispatch` ici ?

2024-07-29 16:34 UTC, ikarius commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
> +    {#if !contactBoxOpen}
nice, ça enlève du code, dont c'est fondamentalement pas mauvais :)

2024-07-29 16:35 UTC, ikarius commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
> +  {/if}
Ok, j'avais pas compris que le fait de fournir un lien et son info remplaçait ce label ...

2024-07-29 16:44 UTC, ikarius commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
>  <h2 class="text-f23 text-white">Mobiliser ce service</h2>
Concernant la gestion du lien de formulaire externe, si on active le lien une première fois :  tout fonctionne correctement.
Par contre, si :  
- on modifie le service pour désactiver le formulaire externe,
- on valide / publie le service,
- puis on revient pour réactiver le formulaire externe
alors :  on retrouve les anciennes valeurs saisies.

Ne faudrait t'il pas effacer leurs valeurs en DB ?

2024-07-30 07:43 UTC, ggounot commented on src/lib/components/display/linkify.svelte
> +            const email = match.replace("mailto:", "");
Oui, j'aurais pu, mais ça aurait sans doute complexifié le code. Je propose de laisser comme ça pour le moment car ça fonctionne et c'est l'essentiel :)

2024-07-30 07:44 UTC, ggounot commented on src/lib/components/display/linkify.svelte
> +  $: parts = linkify();
Yep ! J'ai mis à jour ce code pour que `linkify()` soit appelé à chaque fois que `text` change. Ça n'arrivera pas en principe mais bien gérer la réactivité est plus propre.

2024-07-30 07:46 UTC, ggounot commented on src/lib/components/display/linkify.svelte
> +      rel="noopener ugc"
Oui, on en apprend presque tous les jours sur le web...

2024-07-30 07:55 UTC, ggounot commented on src/lib/validation/schemas/service.ts
> +        "completer-le-formulaire-dadhesion"
Oui, on devrait générer les types automatiquement, ce serait plus propre et plus sûr.

Pour ce cas là, côté front, `beneficiariesAccessModes` est typé avec `BeneficiaryAccessModes` qui est une union des valeurs possibles pour les modes d'orientation bénéficiaire. Donc la valeur « en dur » n'est pas vraiment problématique.

2024-07-30 07:55 UTC, ggounot commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
> +
:+1:

2024-07-30 08:01 UTC, ggounot commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
> +        dispatch("trackMobilisation");
Pour qu'une seule mobilisation soit enregistrée, peu importe le nombre de boutons cliqués sur la fiche service, la fonction qui effectue le _tracking_ (`handleTrackMobilisation()`) au maximum une seule fois (à l'aide du booléen `mobilisationTracked`) se trouve dans le composant parent commun à tous les boutons (`ServiceBody`) et chacun des composants ayant un bouton devant enregistrer une mobilisation émet un événement custom `trackMobilisation` (via `dispatch("trackMobilisation")`) qui est écouté dans `ServiceBody` et branché sur `handleTrackMobilisation()`.

2024-07-30 08:02 UTC, ggounot commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
> +    {#if !contactBoxOpen}
Oui, ça tous ces `div`s pouvaient n'en faire qu'un :)

2024-07-30 08:07 UTC, ikarius commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
> +        dispatch("trackMobilisation");
D'accord, tu interceptes à un plus haut niveau. Merci !

2024-07-30 08:08 UTC, ggounot commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
>  <h2 class="text-f23 text-white">Mobiliser ce service</h2>
C'est une question que je me suis posé. J'ai décidé de les laisser en DB au cas où l'utilisateur veuille retrouver les valeurs précédemment saisies. Penses-tu qu'il serait meilleure pratique d'effacer ces données lorsque le formulaire externe est désactivé ?

2024-07-30 08:10 UTC, ikarius commented on src/routes/(modeles-services)/_common/fields-modalities-beneficiary.svelte
> +          </Checkbox>
Ok, je vois mieux la structure / imbrication du composant maintenant. C'est assez souple en fait.

2024-07-30 08:27 UTC, ikarius requested changes
Grosse PR et beaucoup d'interactions (peut-être encore quelques unes à venir) 👏🏻 
Quelques (petites) remarques par ordre d'importance:
- la persistance des liens externes entre 2 modifications du service : l'état de la base ne reflète pas les données du formulaire. Il faudrait qu'une modification du service RAZ les données des liens externes
- je ne sais pas si les warning Github sur `@html` pouvant mener à une attaque XSS sont visibles de ton coté. Quelque chose à faire la dessus ?

Enfin, c'est une grosse PR en comparaison de la demande, ce qui m'amène à me poser des questions sur notre "agilité" potentielle à modifier cette partie.

Perso, si à l'avenir je vois des modifications lourdes arriver sur la partie service, je demanderais : 
-  de bien vérifier la motivation,
- de commencer à penser à refactoriser / simplifier cette partie

2024-07-30 08:29 UTC, ikarius commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
>  <h2 class="text-f23 text-white">Mobiliser ce service</h2>
A première vue je dirais oui, je voulais juste en discuter. Ca pourrait aussi être fait dans une deuxième phase, tu dois avoir envie de voir autre chose ...

2024-07-30 09:04 UTC, ggounot commented
>     * la persistance des liens externes entre 2 modifications du service : l'état de la base ne reflète pas les données du formulaire. Il faudrait qu'une modification du service RAZ les données des liens externes. A faire dans une autre micro-PR ? Dans ce cas je peux valider celle-ci !

OK, je vais faire les modifs pour que ces données soient supprimées.
 
>     * je ne sais pas si les warning Github sur `@html` pouvant mener à une attaque XSS sont visibles de ton coté. Quelque chose à faire la dessus ?

Oui, eslint me montre ces warnings aussi. L'utilisation des SVG avec `@html` ne me convient pas trop non plus. Je pense changer ça dans le futur pour éviter l'utilisation de `@html` et ces warnings. Mais ce n'est pas urgent ni bloquant pour le moment...

> Enfin, c'est une grosse PR en comparaison de la demande, ce qui m'amène à me poser des questions sur notre "agilité" potentielle à modifier cette partie.
> 
> Perso, si à l'avenir je vois des modifications lourdes arriver sur la partie service, je demanderais :
> 
>     * de bien vérifier la motivation,
> 
>     * de commencer à penser à refactoriser / simplifier cette partie

Oui je suis d'accord avec toi. Cette fonctionnalité était conséquente à implémenter. Je en suis pas sûr cependant qu'on aurait pu la découper davantage qu'en parties formulaire/fiche comme fait avant la fusion des deux.

On aurait pu simplifier la fonctionnalité en amont mais il y a de toute façon toujours des inconnues et du refactoring qui gonfle la PR dans des proportions peu prévisibles.

2024-07-30 09:54 UTC, ggounot commented on src/routes/(modeles-services)/_common/display/service-mobilisation.svelte
>  <h2 class="text-f23 text-white">Mobiliser ce service</h2>
Fait ici : 25ba7d4e0892c4e1e7da1f63ef0dc29260fb74fd

2024-07-30 09:55 UTC, ggounot commented on src/routes/(modeles-services)/_common/fields-modalities-beneficiary.svelte
> +          </Checkbox>
:+1:

2024-07-30 12:35 UTC, ikarius approved these changes

2024-07-30 16:09 UTC, merged