Ajout de labels nationaux "restreints"
gip-inclusion/dora-front pull request #438
Opened 2024-08-15 15:03 UTC by ikarius

La liste des labels nationaux est filtrée lors de la modification d'une
structure.
Elle tient compte des labels nationaux "restreints" (par ex. FT) qui ne
peuvent être choisis par l'utilisateur.

2024-08-15 15:54 UTC, ggounot requested changes

2024-08-15 15:54 UTC, ggounot commented on src/routes/structures/[slug]/editer/+page.svelte
> +  };
Il vaudrait mieux faire le filtrage dans le fichier exact où les données sont utilisées, à savoir ici `structure-edition-fields.svelte`. Et je pense que tu peux simplifier en ne comparant les valeurs.

2024-08-28 09:51 UTC, ggounot submitted a review, later dismissed
Mieux avec ce refactoring ! On pourrait encore simplifier (voir commentaires).

2024-08-28 09:51 UTC, ggounot commented on src/routes/structures/[slug]/editer/structure-edition-fields.svelte
> +  choices={filteredStructuresOptions.typologies}
Je ne vois pas à quoi sert ce changement

2024-09-02 16:23 UTC, ikarius commented on src/routes/structures/[slug]/editer/structure-edition-fields.svelte
> +  choices={filteredStructuresOptions.typologies}
`structureOptions` est la liste brute, et `filteredStructuresOptions` la même, mais sans les labels nationaux.

2024-09-02 16:29 UTC, ikarius commented on src/routes/structures/[slug]/editer/structure-edition-fields.svelte
> +  choices={filteredStructuresOptions.typologies}
Moi non plus à bien y regarder

2024-09-02 16:45 UTC, jbuget commented on src/routes/structures/[slug]/editer/structure-edition-fields.svelte
> +  );
Malheureusement, à part un peu de destructuration, à la rigueur de renommage, et l'utilisation de `some` plutôt que `find` (car le premier renvoie un boolean) je ne vois pas trop comment optimiser ces lignes

2024-09-02 16:46 UTC, jbuget approved these changes
LGTM 🚀

à part une micro-proposition (utiliser `array.some(...)` plutôt que `array.find(...)` pas grand chose à redire

2024-09-05 07:55 UTC, merged